import os

TELEGRAM_SESSION_NAME = './telegram.session'
TELEGRAM_API_ID = os.getenv('TELEGRAM_API_ID')
TELEGRAM_API_HASH = os.getenv('TELEGRAM_API_HASH')
TELEGRAM_SESSION_CHARSET = os.getenv('TELEGRAM_SESSION_CHARSET')
TELEGRAM_SESSION_CONTENT = os.getenv('TELEGRAM_SESSION_CONTENT')
