# Changed
# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: IBCN Checkin

on:
  # push:
  #   branches: [main]
  #pull_request:
  #  branches: [ main ]

  schedule:
    # 以国际标准事件为准，中国北京时间位于东八区，需要加8小时
    # 比如国际时间2020年1月1日21点是北京时间2020年1月2日5点
    # cron: "分 时 日 月 年"
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
        # 并不是同时包含三个环境，而是用三个环境都执行一遍
        # python-version: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 requests telethon
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run
        env:
          TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          TELEGRAM_SESSION_CHARSET: ${{ secrets.TELEGRAM_SESSION_CHARSET }}
          TELEGRAM_SESSION_CONTENT: ${{ secrets.TELEGRAM_SESSION_CONTENT }}

        run: |
          cd ./IBCN/checkin
          python main.py
